"""
Build the per-candidate detail panels for the project page and inject them into
CRBN_Project_site/index.html between its marker comments.

Each panel carries, for one molecule: a 2D depiction drawn from the exact SMILES
that was docked, the PyMOL render of its rank-1 ternary model (produced by 13),
and every measured number the pipeline produced for it -- docking, structure,
upstream pose, registry identity, and the three decision rules.

WHY THIS IS GENERATED RATHER THAN WRITTEN BY HAND. There are 20 molecules and
roughly 25 numbers each. Hand-transcribing 500 figures into HTML is not a task
with a good error rate, and every one of them already exists in a CSV. The page's
prose stays hand-written; only the panels are generated, and they are rebuilt
from the CSVs whenever the pipeline reruns.

The 2D depictions are post-processed so carbon skeletons inherit the page's text
colour via `currentColor` instead of being hard-coded black -- otherwise they
would be near-invisible against the dark theme. Heteroatoms keep RDKit's element
colours, which read on both grounds.

Run with the SYSTEM python (needs rdkit), after 11, 12 and 13:
    /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 \
        "14_build_candidate_panels_(Ryan).py"
"""
import csv
import html
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SITE_DIR = os.path.join(SCRIPT_DIR, "CRBN_Project_site")
INDEX_HTML = os.path.join(SITE_DIR, "index.html")
IMG_DIR = os.path.join(SITE_DIR, "img")

BUY_LIST = os.path.join(SCRIPT_DIR, "final_buy_list_lock_v1_top20_(Ryan).csv")
ANNOTATED = os.path.join(SCRIPT_DIR, "Final Buy List for Purchase (annotated).csv")
FINALISTS = os.path.join(SCRIPT_DIR, "08_final_ternary_with_ligand_results_(Ryan).csv")
CROSSCHECK = os.path.join(SCRIPT_DIR, "08_crosscheck_results_(Ryan).csv")

START = "<!-- CANDIDATE-PANELS:START (generated by 14_build_candidate_panels) -->"
END = "<!-- CANDIDATE-PANELS:END -->"

# One-line rationale per molecule, mirroring the shortlist table's reason column.
WHY = {
    "RW_708": "Best score of anything docked, and last of the 18 on structure.",
    "RW_491": "Second-best score; structure axis still below the line.",
    "RW_1987": "Top-5 on dock, structure and pose at once. Strongest all-round profile.",
    "RW_1959": "Clears all three, structure by only +0.01.",
    "RW_465": "Clears all three, and the #2 upstream pose of the 18.",
    "RW_1992": "Clears all three with the tightest funnel of the four.",
    "RW_2392": "Clears the control bar on score alone; fails both other axes.",
    "RW_234": "Misses the control bar by 0.02 units.",
    "RW_2123": "Passes nothing; mid-pack on every axis at once.",
    "RW_1668": "The structure extreme: best structure score of all 21.",
    "RW_445": "Second-best structure score and second-largest interface.",
    "RW_779": "Good structure, weak upstream pose. Bromo member of the halogen series.",
    "RW_381": "The pose extreme: best upstream Vina pose of all 18.",
    "RW_1092": "Strong structure and pose, held off only by docking rank.",
    "RW_1078": "Middling throughout; the fluoro member of the halogen series.",
    "RW_80": "Worst upstream pose of the 18, but a well-converged funnel.",
    "RW_72": "Positional isomer of the Z6466608628 positive control.",
    "RW_672": "Weakest of the 18; above the noise floor.",
    "TZ_6": "From the second screen. Below the noise floor.",
    "TZ_118": "From the second screen. Lowest structure score of all 21.",
}

NOISE_FLOOR = -112.202
GLUE_BAR = -125.610


def read_csv(path):
    if not os.path.exists(path):
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def depiction_svg(smiles, width=300, height=210):
    """2D structure drawn from the docked SMILES, themed for the page.

    RDKit hard-codes black for the carbon skeleton, which disappears on the dark
    theme, and paints an opaque white background rect that would sit as a white
    block inside a dark panel. Both are stripped here: the background is removed
    and every black stroke/fill becomes `currentColor`, so the skeleton follows
    the panel's text colour in whichever theme is active."""
    from rdkit import Chem
    from rdkit.Chem import rdDepictor
    from rdkit.Chem.Draw import rdMolDraw2D

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return ""
    rdDepictor.Compute2DCoords(mol)
    rdDepictor.StraightenDepiction(mol)
    drawer = rdMolDraw2D.MolDraw2DSVG(width, height)
    opts = drawer.drawOptions()
    opts.clearBackground = False
    opts.bondLineWidth = 1.5
    opts.multipleBondOffset = 0.14
    opts.padding = 0.06
    rdMolDraw2D.PrepareAndDrawMolecule(drawer, mol)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()

    svg = re.sub(r"<rect[^>]*>\s*", "", svg, count=1)          # opaque background
    svg = svg.replace("<?xml version='1.0' encoding='iso-8859-1'?>", "").strip()
    svg = re.sub(r"(stroke|fill):#000000", r"\1:currentColor", svg)
    svg = svg.replace("stroke:#000000", "stroke:currentColor")
    svg = svg.replace("<svg ", '<svg class="mol2d" role="img" ', 1)
    return svg


def fmt(value, digits=None, dash="&mdash;"):
    if value in (None, "", "-"):
        return dash
    if digits is None:
        return html.escape(str(value))
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return html.escape(str(value))


def rule_pill(passed, label):
    state = "ok" if passed == "yes" else "no"
    mark = "&check;" if passed == "yes" else "&times;"
    return f'<span class="pill p-{state}"><b>{mark}</b>{label}</span>'


def panel(row, extra, dockq):
    name = row["name"]
    smiles = row["smiles"]
    img = f"img/{name}.png"
    has_img = os.path.exists(os.path.join(IMG_DIR, f"{name}.png"))
    score = float(row["haddock_mean_best10"])

    if score > NOISE_FLOOR:
        verdict = ('<p class="flagline">Above the &minus;112.2 noise floor &mdash; this score is '
                   'not distinguishable from a degron-dead negative control.</p>')
    elif score < GLUE_BAR:
        verdict = ('<p class="okline">Clears the &minus;125.6 control bar set by the strongest '
                   'positive control.</p>')
    else:
        verdict = ('<p class="flagline">Between the noise floor and the &minus;125.6 control bar.</p>')

    cas = extra.get("cas_number", "")
    registry = ("Not a registered substance &mdash; custom synthesis"
                if cas.startswith("none") else html.escape(cas))

    def cell(label, value, note=""):
        note_html = f'<span class="dn">{note}</span>' if note else ""
        return f'<div class="d"><span class="dl">{label}</span><b>{value}</b>{note_html}</div>'

    docking = "".join([
        cell("Mean, best 10", fmt(score, 3), f"rank #{row['dock_rank_of_18']} &middot; z {fmt(row['dock_z'], 2)}"),
        cell("Best single model", fmt(row["haddock_best_model"], 3)),
        cell("Spread (sd)", fmt(row["sd_best_10"], 2), "lower is a tighter funnel"),
        cell("Models scored", fmt(row["n_models"])),
    ])
    structure = "".join([
        cell("Structure axis", fmt(row["structure_score_z"], 3), f"rank #{row['structure_rank_of_18']}"),
        cell("Buried interface", f'{fmt(row["bsa_mean_best10"], 0)} &Aring;&sup2;'),
        cell("Top cluster", f'{float(row["top_cluster_fraction"]) * 100:.0f}%', "of all models"),
        cell("Restraint energy", fmt(row["air_mean_best10"], 1), "AIR, lower is better"),
        cell("van der Waals", fmt(row["vdw_mean_best10"], 2)),
        cell("DockQ vs 9DWV", fmt(dockq, 3), "diagnostic only, not ranked on"),
    ])
    upstream = "".join([
        cell("Vina, CRBN pocket", f'{fmt(row["vina_crbn_affinity"], 2)} kcal/mol', f"rank #{row['vina_rank_of_18']}"),
        cell("Vina, combined", f'{fmt(row["vina_combined_affinity"], 2)} kcal/mol'),
        cell("Pose overlap", fmt(row["degron_contact_overlap"], 2)),
        cell("P(CRBN glue)", fmt(row["p_crbn_glue"]), "classifier, saturated &mdash; weak signal"),
    ])
    identity = "".join([
        cell("Formula", html.escape(extra.get("molecular_formula", "&mdash;"))),
        cell("Molecular weight", fmt(extra.get("molecular_weight"), 2)),
        cell("CAS", registry),
        cell("Pipeline ID", html.escape(row["run_name"]), "name used in every run directory"),
    ])

    rules = "".join([
        rule_pill(row["rule_a_upstream_crbn_pose"], "Credible CRBN pose"),
        rule_pill(row["rule_b_structure_z_ge_0"], "Structure &ge; 0"),
        rule_pill(row["rule_c_beats_Z6466608628"], "Beats control bar"),
    ])

    img_block = (
        f'<figure class="v3d"><img src="{img}" width="620" height="460" loading="lazy" decoding="async"'
        f' alt="Rank-1 ternary model of {html.escape(name)}: CRBN in teal, PPIL4 in indigo,'
        f' the ligand in ochre at the interface.">'
        f'<figcaption>Rank-1 ternary model. CRBN <span class="sw-c"></span>, '
        f'PPIL4 <span class="sw-p"></span>, ligand <span class="sw-l"></span>. All 20 renders share '
        f'one camera after superposition on CRBN, so PPIL4&rsquo;s position is comparable between '
        f'molecules.</figcaption></figure>'
    ) if has_img else '<p class="caption">No render available for this molecule.</p>'

    return f"""<details class="cand" id="c-{html.escape(name)}">
  <summary>
    <span class="c-id">{html.escape(name)}</span>
    <span class="c-chem">{html.escape(row["chemotype"])}</span>
    <span class="c-score mono">{fmt(score, 1)}</span>
    <span class="c-rules mono">{row["rules_passed"]}/3</span>
  </summary>
  <div class="c-body">
    <p class="c-why">{html.escape(WHY.get(name, ""))}</p>
    {verdict}
    <div class="c-rulerow">{rules}</div>
    <div class="c-vis">
      <figure class="v2d">{depiction_svg(smiles)}<figcaption>2D structure, drawn from the exact
        SMILES that was docked.</figcaption></figure>
      {img_block}
    </div>
    <div class="c-data">
      <div class="dgroup"><h4>Ternary docking</h4><div class="dgrid">{docking}</div></div>
      <div class="dgroup"><h4>Structure quality</h4><div class="dgrid">{structure}</div></div>
      <div class="dgroup"><h4>Upstream evidence</h4><div class="dgrid">{upstream}</div></div>
      <div class="dgroup"><h4>Identity</h4><div class="dgrid">{identity}</div></div>
    </div>
    <p class="c-smiles"><span class="dl">SMILES</span><code>{html.escape(smiles)}</code></p>
    <p class="c-smiles"><span class="dl">InChIKey</span><code>{html.escape(extra.get("inchikey", ""))}</code></p>
  </div>
</details>"""


def main():
    rows = [r for r in read_csv(BUY_LIST) if r["role"] in ("candidate", "crosscheck")]
    if not rows:
        sys.exit(f"No candidates in {os.path.basename(BUY_LIST)} -- run 11 first.")
    rows.sort(key=lambda r: float(r["haddock_mean_best10"]))

    extras = {r["name"]: r for r in read_csv(ANNOTATED)}
    dockq = {}
    for path in (FINALISTS, CROSSCHECK):
        for r in read_csv(path):
            dockq[r["molecule"]] = r.get("dockq_vs_9dwv", "")

    missing_img = [r["name"] for r in rows if not os.path.exists(os.path.join(IMG_DIR, f"{r['name']}.png"))]
    if missing_img:
        print(f"NOTE: no render for {', '.join(missing_img)} -- run 13 under PyMOL first.")

    panels = "\n".join(panel(r, extras.get(r["name"], {}), dockq.get(r["run_name"], "")) for r in rows)

    with open(INDEX_HTML) as f:
        page = f.read()
    if START not in page or END not in page:
        sys.exit(f"Marker comments not found in {os.path.basename(INDEX_HTML)}. Expected:\n  {START}\n  {END}")
    head, rest = page.split(START, 1)
    _, tail = rest.split(END, 1)
    page = f"{head}{START}\n{panels}\n{END}{tail}"
    with open(INDEX_HTML, "w") as f:
        f.write(page)

    total_kb = len(page.encode()) / 1024
    print(f"Injected {len(rows)} candidate panels into {os.path.relpath(INDEX_HTML, SCRIPT_DIR)}")
    print(f"  page is now {total_kb:.0f} KB; renders referenced from img/ ({len(rows) - len(missing_img)} present)")


if __name__ == "__main__":
    main()
