"""
Build the per-candidate detail panels for the project page and inject them into
CRBN_Project_site/index.html between its marker comments.

Each panel carries, for one molecule: a 2D depiction drawn from the exact SMILES
that was docked, the PyMOL render of its rank-1 ternary model (produced by 13),
and every measured number the pipeline produced for it -- docking, structure,
upstream pose, registry identity, and the three decision rules.

WHY THIS IS GENERATED RATHER THAN WRITTEN BY HAND. There are 20 molecules and
roughly 25 numbers each. Hand-transcribing 500 figures into HTML is not a task
with a good error rate, and every one of them already exists in a CSV. The page's
prose stays hand-written; only the panels are generated, and they are rebuilt
from the CSVs whenever the pipeline reruns.

The 2D depictions are post-processed so carbon skeletons inherit the page's text
colour via `currentColor` instead of being hard-coded black -- otherwise they
would be near-invisible against the dark theme. Heteroatoms keep RDKit's element
colours, which read on both grounds.

Run with the SYSTEM python (needs rdkit), after 11, 12 and 13:
    /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 \
        "14_build_candidate_panels_(Ryan).py"
"""
import csv
import hashlib
import html
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SITE_DIR = os.path.join(SCRIPT_DIR, "CRBN_Project_site")
INDEX_HTML = os.path.join(SITE_DIR, "index.html")
IMG_DIR = os.path.join(SITE_DIR, "img")

BUY_LIST = os.path.join(SCRIPT_DIR, "final_buy_list_lock_v1_top20_(Ryan).csv")
ANNOTATED = os.path.join(SCRIPT_DIR, "Final Buy List for Purchase (annotated).csv")
FINALISTS = os.path.join(SCRIPT_DIR, "08_final_ternary_with_ligand_results_(Ryan).csv")
CROSSCHECK = os.path.join(SCRIPT_DIR, "08_crosscheck_results_(Ryan).csv")
CONTROLS_CSV = os.path.join(SCRIPT_DIR, "08_controls_results_(Ryan).csv")

START = "<!-- CANDIDATE-PANELS:START (generated by 14_build_candidate_panels) -->"
END = "<!-- CANDIDATE-PANELS:END -->"
CTRL_START = "<!-- CONTROL-PANELS:START (generated by 14_build_candidate_panels) -->"
CTRL_END = "<!-- CONTROL-PANELS:END -->"

# The calibration set. `sets` is what each control establishes -- these are the
# molecules the candidates are judged against, so what each one tests matters
# more than its score. FPFT-2216's SMILES is RCSB ligand A1BC8, cross-checked
# against the atom composition of the cached 9DWV structure (see 09).
CONTROL_META = {
    "FPFT_2216_positive_control": {
        "label": "FPFT-2216",
        "kind": "Positive control &middot; the real drug",
        "smiles": "COc1cscc1c2cn(nn2)[C@H]3CCC(=O)NC3=O",
        "sets": "The methodology check. This is the compound the CRBN&ndash;PPIL4 ternary complex "
                "was actually solved with, so it is the one molecule whose right answer is known "
                "independently. Recovering the experimental architecture from it is what licenses "
                "trusting the protocol at all &mdash; and nothing more than that.",
    },
    "Z6466608628_positive_control": {
        "label": "Z6466608628",
        "kind": "Positive control &middot; commercial glue",
        "smiles": "",
        "sets": "<strong>The usable bar.</strong> The strongest control by docking score, so it is "
                "what a candidate has to beat to mean anything. Seven candidates clear it.",
    },
    "TM-04-064-02_positive_control": {
        "label": "TM-04-064-02",
        "kind": "Positive control &middot; adenine-linked thalidomide",
        "smiles": "",
        "sets": "A second, structurally unrelated positive: a large adenine-linked degrader. Scores "
                "below the noise floor, which is itself informative about how much the score tracks "
                "size and interface rather than glue activity.",
    },
    "negctrl_no_glutarimide": {
        "label": "Degron removed",
        "kind": "Negative control &middot; cannot bind CRBN",
        "smiles": "",
        "sets": "<strong>The noise floor.</strong> The glutarimide degron is deleted, so this "
                "molecule physically cannot engage CRBN. It nonetheless outscores FPFT-2216 &mdash; "
                "which is why anything above roughly &minus;112 is not distinguishable from an inert "
                "molecule, and why &ldquo;beats the real drug&rdquo; is a meaningless claim.",
    },
    "negctrl_no_ppil4_arm": {
        "label": "No PPIL4 arm",
        "kind": "Negative control &middot; nothing to recruit with",
        "smiles": "",
        "sets": "Keeps the CRBN degron but removes the arm that would present a surface to PPIL4. "
                "Isolates how much of a candidate's score comes from the degron alone.",
    },
    "negctrl_no_crbn_ppil4_arm": {
        "label": "Both handles stripped",
        "kind": "Negative control &middot; bare fragment",
        "smiles": "",
        "sets": "The FPFT core fragment with both functional handles gone &mdash; the worst score of "
                "anything docked, as it should be. The floor of the whole scale.",
    },
}

REFERENCE_NOTE = (
    "The experimental CRBN&ndash;FPFT-2216&ndash;PPIL4 ternary complex, PDB <strong>9DWV</strong>. "
    "This is not a prediction: it is the deposited structure, with the real FPFT-2216 taken from the "
    "deposited chemical component rather than from any docking run. It is what every model on this "
    "page is scored against, and it is superposed into the same CRBN frame as the rest, so it can be "
    "compared directly against them. Its PPIL4 chain is short because only the RRM domain was "
    "resolved experimentally, while the docked models carry a full AlphaFold PPIL4."
)

# One-line rationale per molecule, mirroring the shortlist table's reason column.
WHY = {
    "RW_708": "Best score of anything docked, and last of the 18 designed candidates on structure.",
    "RW_491": "Second-best score; structure axis still below the line.",
    "RW_1987": "Top-5 on dock, structure and pose at once. Strongest all-round profile.",
    "RW_1959": "Clears all three, structure by only +0.01.",
    "RW_465": "Clears all three, and the #2 upstream pose of the 18.",
    "RW_1992": "Clears all three with the tightest funnel of the four.",
    "RW_2392": "Clears the control bar on score alone; fails both other axes.",
    "RW_234": "Misses the control bar by 0.02 units.",
    "RW_2123": "Passes nothing; mid-pack on every axis at once.",
    "RW_1668": "The structure extreme: best structure score of all 20 scored molecules.",
    "RW_445": "Second-best structure score and second-largest interface.",
    "RW_779": "Good structure, weak upstream pose. Bromo member of the halogen series.",
    "RW_381": "The pose extreme: best upstream Vina pose of the 18 designed candidates.",
    "RW_1092": "Strong structure and pose, held off only by docking rank.",
    "RW_1078": "Middling throughout; the fluoro member of the halogen series.",
    "RW_80": "Worst upstream pose of the 18, but a well-converged funnel.",
    "RW_72": "Positional isomer of the Z6466608628 positive control.",
    "RW_672": "Weakest of the 18; does not clear the noise floor.",
    "TZ_6": "From the second screen. Does not clear the noise floor.",
    "TZ_118": "From the second screen. Lowest structure score of all 20 scored molecules.",
}

NOISE_FLOOR = -112.202
GLUE_BAR = -125.610


def read_csv(path):
    if not os.path.exists(path):
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def depiction_svg(smiles, label="", width=300, height=210):
    """2D structure drawn from the docked SMILES, themed for the page.

    RDKit hard-codes black for the carbon skeleton, which disappears on the dark
    theme, and paints an opaque white background rect that would sit as a white
    block inside a dark panel. Both are stripped here: the background is removed
    and every black stroke/fill becomes `currentColor`, so the skeleton follows
    the panel's text colour in whichever theme is active."""
    from rdkit import Chem
    from rdkit.Chem import rdDepictor
    from rdkit.Chem.Draw import rdMolDraw2D

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return ""
    rdDepictor.Compute2DCoords(mol)
    rdDepictor.StraightenDepiction(mol)
    drawer = rdMolDraw2D.MolDraw2DSVG(width, height)
    opts = drawer.drawOptions()
    opts.clearBackground = False
    opts.bondLineWidth = 1.5
    opts.multipleBondOffset = 0.14
    opts.padding = 0.06
    rdMolDraw2D.PrepareAndDrawMolecule(drawer, mol)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()

    svg = re.sub(r"<rect[^>]*>\s*", "", svg, count=1)          # opaque background
    svg = svg.replace("<?xml version='1.0' encoding='iso-8859-1'?>", "").strip()
    svg = re.sub(r"(stroke|fill):#000000", r"\1:currentColor", svg)
    svg = svg.replace("stroke:#000000", "stroke:currentColor")
    svg = svg.replace("<svg ", '<svg class="mol2d" role="img" ', 1)
    # role="img" without an accessible name announces as a bare "image"; with 27
    # depictions on the page that is 27 meaningless stops for a screen reader.
    if label:
        svg = re.sub(r"(<svg\b[^>]*>)", r"\1<title>2D structure of " + html.escape(label) + "</title>",
                     svg, count=1)
    return svg


def viewer_block(key, label, has_poster, structure_key=None):
    """An interactive 3D viewer, with the static PyMOL render underneath it as
    the no-JavaScript fallback. The render is inside <noscript> rather than
    being replaced at runtime, so a reader without JS still sees the structure
    and a reader with JS never downloads the image."""
    structure_key = structure_key or key
    poster = (
        f'<noscript><img class="v3d-poster" src="img/{key}.png" width="620" height="460"'
        f' alt="{html.escape(label)} of {html.escape(key)}: CRBN in teal, PPIL4 in indigo,'
        f' ligand in ochre at the interface."></noscript>'
    ) if has_poster else ""
    return (
        f'<figure class="v3d">'
        f'<div class="v3d-host" data-structure="{html.escape(structure_key)}">'
        f'<p class="v3d-msg">Loading 3D model&hellip;</p></div>{poster}'
        f'<figcaption><b>{html.escape(label)}.</b> CRBN <span class="sw-c"></span>, '
        f'PPIL4 <span class="sw-p"></span>, ligand <span class="sw-l"></span>. '
        f'<span class="v3d-help">Drag to rotate &middot; scroll to zoom &middot; double-click to '
        f'reset &middot; arrow keys when focused.</span> Every structure is superposed on CRBN, so '
        f'PPIL4&rsquo;s position is comparable between them.</figcaption></figure>'
    )


def fmt(value, digits=None, dash="&mdash;"):
    if value in (None, "", "-"):
        return dash
    if digits is None:
        return html.escape(str(value))
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return html.escape(str(value))


def rule_pill(passed, label):
    state = "ok" if passed == "yes" else "no"
    mark = "&check;" if passed == "yes" else "&times;"
    return f'<span class="pill p-{state}"><b>{mark}</b>{label}</span>'


def panel(row, extra, dockq):
    name = row["name"]
    smiles = row["smiles"]
    img = f"img/{name}.png"
    has_img = os.path.exists(os.path.join(IMG_DIR, f"{name}.png"))
    score = float(row["haddock_mean_best10"])

    if score > NOISE_FLOOR:
        verdict = ('<p class="flagline">Does not clear the &minus;112.20 noise floor &mdash; this '
                   'score is not distinguishable from a degron-dead negative control.</p>')
    elif score < GLUE_BAR:
        verdict = ('<p class="okline">Clears the &minus;125.61 control bar set by the strongest '
                   'positive control.</p>')
    else:
        verdict = ('<p class="flagline">Between the noise floor and the &minus;125.6 control bar.</p>')

    cas = extra.get("cas_number", "")
    registry = (html.escape(cas) if extra.get("registered") == "yes"
                else "Not a registered substance &mdash; custom synthesis")

    def cell(label, value, note=""):
        note_html = f'<span class="dn">{note}</span>' if note else ""
        return f'<div class="d"><span class="dl">{label}</span><b>{value}</b>{note_html}</div>'

    docking = "".join([
        cell("Mean, best 10", fmt(score, 3),
             f"#{row['dock_rank_of_18']} against the 18 designed &middot; z {fmt(row['dock_z'], 2)}"),
        cell("Best single model", fmt(row["haddock_best_model"], 3)),
        cell("Spread (sd)", fmt(row["sd_best_10"], 2), "lower is a tighter funnel"),
        cell("Models scored", fmt(row["n_models"])),
    ])
    structure = "".join([
        cell("Structure axis", fmt(row["structure_score_z"], 3),
             f"#{row['structure_rank_of_18']} against the 18 designed"),
        cell("Buried interface", f'{fmt(row["bsa_mean_best10"], 0)} &Aring;&sup2;'),
        cell("Top cluster", f'{float(row["top_cluster_fraction"]) * 100:.0f}%', "of all models"),
        cell("Restraint energy", fmt(row["air_mean_best10"], 1), "AIR, lower is better"),
        cell("van der Waals", fmt(row["vdw_mean_best10"], 2)),
        cell("DockQ vs 9DWV", fmt(dockq, 3), "diagnostic only, not ranked on"),
    ])
    upstream = "".join([
        cell("Vina, CRBN pocket", f'{fmt(row["vina_crbn_affinity"], 2)} kcal/mol',
             f"#{row['vina_rank_of_18']} against the 18 designed"),
        cell("Vina, combined", f'{fmt(row["vina_combined_affinity"], 2)} kcal/mol'),
        cell("Pose overlap", fmt(row["degron_contact_overlap"], 2)),
        cell("RF glue-likeness", fmt(row["p_crbn_glue"]),
             "vote fraction, uncalibrated &mdash; saturated across the library, weak signal"),
    ])
    identity = "".join([
        cell("Formula", html.escape(extra.get("molecular_formula", "&mdash;"))),
        cell("Molecular weight", fmt(extra.get("molecular_weight"), 2)),
        cell("CAS", registry),
        cell("Pipeline ID", html.escape(row["run_name"]), "name used in every run directory"),
    ])

    rules = "".join([
        rule_pill(row["rule_a_upstream_crbn_pose"], "Credible CRBN pose"),
        rule_pill(row["rule_b_structure_z_ge_0"], "Structure &ge; 0"),
        rule_pill(row["rule_c_beats_Z6466608628"], "Beats control bar"),
    ])

    img_block = viewer_block(name, "Rank-1 ternary model", has_img)

    return f"""<details class="cand" id="c-{html.escape(name)}">
  <summary>
    <span class="c-id">{html.escape(name)}</span>
    <span class="c-chem">{html.escape(row["chemotype"])}</span>
    <span class="c-score mono">{fmt(score, 1)}</span>
    <span class="c-rules mono">{row["rules_passed"]}/3</span>
  </summary>
  <div class="c-body">
    <p class="c-why">{html.escape(WHY.get(name, ""))}</p>
    {verdict}
    <div class="c-rulerow">{rules}</div>
    <div class="c-vis">
      <figure class="v2d">{depiction_svg(smiles, name)}<figcaption>2D structure, drawn from the exact
        SMILES that was docked.</figcaption></figure>
      {img_block}
    </div>
    <div class="c-data">
      <div class="dgroup"><h4>Ternary docking</h4><div class="dgrid">{docking}</div></div>
      <div class="dgroup"><h4>Structure quality</h4><div class="dgrid">{structure}</div></div>
      <div class="dgroup"><h4>Upstream evidence</h4><div class="dgrid">{upstream}</div></div>
      <div class="dgroup"><h4>Identity</h4><div class="dgrid">{identity}</div></div>
    </div>
    <p class="c-smiles"><span class="dl">SMILES</span><code>{html.escape(smiles)}</code></p>
    <p class="c-smiles"><span class="dl">InChIKey</span><code>{html.escape(extra.get("inchikey", ""))}</code></p>
  </div>
</details>"""


def control_panel(row, meta, smiles, has_img):
    """One calibration molecule: what it establishes, its structure, its model."""
    name = row["molecule"]
    score = float(row["mean_best_10"]) if row["mean_best_10"] not in ("", "-") else None

    def cell(label, value, note=""):
        note_html = f'<span class="dn">{note}</span>' if note else ""
        return f'<div class="d"><span class="dl">{label}</span><b>{value}</b>{note_html}</div>'

    numbers = "".join([
        cell("Mean, best 10", fmt(score, 3)),
        cell("Best single model", fmt(row["best_haddock"], 3)),
        cell("Spread (sd)", fmt(row["sd_best_10"], 2)),
        cell("DockQ vs 9DWV", fmt(row["dockq_vs_9dwv"], 3), "diagnostic only"),
        cell("Models scored", fmt(row["n_models"])),
    ])
    two_d = (f'<figure class="v2d">{depiction_svg(smiles, meta["label"])}<figcaption>2D structure, '
             f'drawn from the SMILES that was docked.</figcaption></figure>') if smiles else ""

    return f"""<details class="cand ctrl" id="c-{html.escape(name)}">
  <summary>
    <span class="c-id">{meta['label']}</span>
    <span class="c-chem">{meta['kind']}</span>
    <span class="c-score mono">{fmt(score, 1)}</span>
    <span class="c-rules mono"></span>
  </summary>
  <div class="c-body">
    <p class="c-why">{meta['sets']}</p>
    <div class="c-vis">
      {two_d}
      {viewer_block(name, "Rank-1 ternary model", has_img)}
    </div>
    <div class="c-data"><div class="dgroup"><h4>Ternary docking</h4>
      <div class="dgrid">{numbers}</div></div></div>
  </div>
</details>"""


def reference_panel():
    return f"""<details class="cand ref" id="c-9DWV_reference">
  <summary>
    <span class="c-id">9DWV</span>
    <span class="c-chem">Experimental reference &middot; not a prediction</span>
    <span class="c-score mono">&mdash;</span>
    <span class="c-rules mono"></span>
  </summary>
  <div class="c-body">
    <p class="c-why">{REFERENCE_NOTE}</p>
    <div class="c-vis">
      <figure class="v2d">{depiction_svg(CONTROL_META['FPFT_2216_positive_control']['smiles'], 'FPFT-2216')}
        <figcaption>FPFT-2216, the ligand in the deposited structure.</figcaption></figure>
      {viewer_block("9DWV_reference", "Experimental structure (PDB 9DWV)", False)}
    </div>
  </div>
</details>"""


def stamp_asset_versions(page):
    """Point the script tag at content-hashed URLs for viewer.js and
    structures.json.

    index.html changes on every rebuild so browsers re-fetch it, but the two
    asset files are separate requests and get served from cache -- which is how
    a rebuilt page ends up running the previous viewer against the previous
    data. Worse, a cached viewer paired with a rebuilt schema silently draws
    nothing rather than failing loudly. Hashing the contents into the query
    string makes the URL change exactly when the file does."""
    def digest(path):
        if not os.path.exists(path):
            return "0"
        with open(path, "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()[:10]

    viewer_v = digest(os.path.join(SITE_DIR, "viewer.js"))
    data_v = digest(os.path.join(SITE_DIR, "structures.json"))
    # One version for the whole lib/ directory: three.js and its two loaders are
    # only ever upgraded together, so a single stamp is enough and keeps the tag
    # readable. Mesh URLs carry their own hash, stamped by 16.
    lib_v = hashlib.sha256(b"".join(
        open(os.path.join(SITE_DIR, "lib", n), "rb").read()
        for n in sorted(os.listdir(os.path.join(SITE_DIR, "lib")))
        if n.endswith(".js")
    )).hexdigest()[:10] if os.path.isdir(os.path.join(SITE_DIR, "lib")) else "0"
    tag = (f'<script src="viewer.js?v={viewer_v}" '
           f'data-structures="structures.json?v={data_v}" '
           f'data-lib="lib" data-libv="{lib_v}" defer></script>')
    page, n = re.subn(r'<script src="viewer\.js[^"]*"[^>]*></script>', tag, page)
    if not n:
        page = page.replace("</body>", tag + "\n\n</body>", 1)
    print(f"  assets stamped: viewer.js?v={viewer_v}, structures.json?v={data_v}")
    return page


def inject(page, start, end, body, what):
    if start not in page or end not in page:
        sys.exit(f"Marker comments for {what} not found. Expected:\n  {start}\n  {end}")
    head, rest = page.split(start, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{start}\n{body}\n{end}{tail}"


def main():
    rows = [r for r in read_csv(BUY_LIST) if r["role"] in ("candidate", "crosscheck")]
    if not rows:
        sys.exit(f"No candidates in {os.path.basename(BUY_LIST)} -- run 11 first.")
    rows.sort(key=lambda r: float(r["haddock_mean_best10"]))

    extras = {r["name"]: r for r in read_csv(ANNOTATED)}
    dockq = {}
    for path in (FINALISTS, CROSSCHECK):
        for r in read_csv(path):
            dockq[r["molecule"]] = r.get("dockq_vs_9dwv", "")

    missing_img = [r["name"] for r in rows if not os.path.exists(os.path.join(IMG_DIR, f"{r['name']}.png"))]
    if missing_img:
        print(f"NOTE: no render for {', '.join(missing_img)} -- run 13 under PyMOL first.")

    panels = "\n".join(panel(r, extras.get(r["name"], {}), dockq.get(r["run_name"], "")) for r in rows)

    # Controls: SMILES come from the buy list where present, and from
    # CONTROL_META for FPFT-2216, which is docked but never bought (it is not
    # commercially available) so it has no buy-list row.
    buy_smiles = {r["name"]: r["smiles"] for r in read_csv(BUY_LIST)}
    control_rows = read_csv(CONTROLS_CSV)
    controls_html = []
    for row in sorted(control_rows, key=lambda r: float(r["mean_best_10"] or 0)):
        meta = CONTROL_META.get(row["molecule"])
        if meta is None:
            print(f"NOTE: no description for control {row['molecule']} -- skipped")
            continue
        smiles = meta["smiles"] or buy_smiles.get(row["molecule"], "")
        if not smiles:
            print(f"NOTE: no SMILES for control {row['molecule']} -- 2D structure omitted")
        has_img = os.path.exists(os.path.join(IMG_DIR, f"{row['molecule']}.png"))
        controls_html.append(control_panel(row, meta, smiles, has_img))
    controls_block = reference_panel() + "\n" + "\n".join(controls_html)

    with open(INDEX_HTML) as f:
        page = f.read()
    page = inject(page, START, END, panels, "candidate panels")
    page = inject(page, CTRL_START, CTRL_END, controls_block, "control panels")
    page = stamp_asset_versions(page)
    with open(INDEX_HTML, "w") as f:
        f.write(page)

    total_kb = len(page.encode()) / 1024
    print(f"Injected into {os.path.relpath(INDEX_HTML, SCRIPT_DIR)}:")
    print(f"  {len(rows)} candidate panels")
    print(f"  {len(controls_html)} control panels + the 9DWV reference")
    print(f"  page is now {total_kb:.0f} KB; 3D served from structures.json via viewer.js")


if __name__ == "__main__":
    main()
